==212897== Invalid read of size 4
==212897==    at 0x403FE7: imprimirTPersona(rep_persona*) (persona.cpp:29)
==212897==    by 0x403264: main_maxIdPersonaArbolPersonas(rep_personasAbb*) (principal.cpp:808)
==212897==    by 0x401C5E: main (principal.cpp:351)
==212897==  Address 0x4 is not stack'd, malloc'd or (recently) free'd
==212897== 
==212897== 
==212897== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==212897==  Access not within mapped region at address 0x4
==212897==    at 0x403FE7: imprimirTPersona(rep_persona*) (persona.cpp:29)
==212897==    by 0x403264: main_maxIdPersonaArbolPersonas(rep_personasAbb*) (principal.cpp:808)
==212897==    by 0x401C5E: main (principal.cpp:351)
==212897==  If you believe this happened as a result of a stack
==212897==  overflow in your program's main thread (unlikely but
==212897==  possible), you can try to increase the size of the
==212897==  main thread stack using the --main-stacksize= flag.
==212897==  The main thread stack size used in this run was 8388608.
==212897== 260 (120 direct, 140 indirect) bytes in 1 blocks are definitely lost in loss record 4 of 7
==212897==    at 0x4843FF5: operator new(unsigned long) (vg_replace_malloc.c:434)
==212897==    by 0x403F5B: crearTPersona(unsigned int, unsigned int, char const*, rep_agendaLS*) (persona.cpp:12)
==212897==    by 0x4025E2: main_crearPersona(rep_persona*&, rep_agendaLS*&) (principal.cpp:570)
==212897==    by 0x401688: main (principal.cpp:231)
==212897== 
timeout: la orden monitorizada ha volcado un 'core'
